export const aiInput = (
	<div>
		<p>
			This node serves as an input mechanism for the AI, providing data
			for processing and execution. Users can feed relevant information to
			the AI for analysis,chat processing, task execution, or other
			specified actions within the platform.
		</p>
	</div>
);
export const aiKnowledgeRetrival = (
	<div>
		<p>
			This node employs RAG (Retrieval-Augmented Generation) retrieval for
			processing user-customized data into actionable knowledge. It's
			designed to transform user-provided data into processed knowledge,
			utilizing advanced retrieval and generative mechanisms within the
			platform.
		</p>
	</div>
);
export const aiPlugin = (
	<div>
		<p>
			This node acts as a bridge between plugins, enabling CRUD (Create,
			Read, Update, Delete) operations. It facilitates connectivity and
			allows seamless interaction between different plugins with AI,
			empowering AI to perform various data operations across integrated
			platforms.
		</p>
	</div>
);
export const aiExtendAgent = (
	<div>
		<p>
			This node establishes communication between different AIs, enabling
			data transfer and collaboration. Note: Use this feature for
			executing highly complex tasks that necessitate interaction between
			multiple AIs. Exercise caution and employ this connection only when
			essential for intricate operations.
		</p>
	</div>
);

export const aiSystemPrompt = (
	<div>
		<p>
			This node allows users to configure system prompts dictating the
			AI's behavior and response patterns. Users can craft prompts that
			steer the AI's actions and guide its behavior within the system.
			Customize these prompts to influence the AI's output and
			functionalities, tailoring its behavior to suit specific
			requirements or tasks.
		</p>
	</div>
);

export const aiOutput = (
	<div>
		<p>
			This node presents the conclusive output generated by the AI after
			completing all assigned tasks and processes. It serves as the
			endpoint.
		</p>
	</div>
);
